### ISSUE TITLE
Merge listeners for onConnect and onDisconnect

### ISSUE THREAD

**Issue by morrieinmaas** [animo/react-native-ble-didcomm#29]
see also [this comment](https://github.com/animo/react-native-ble-didcomm/pull/27/files#r1088951180)

**Comment by morrieinmaas** [comment]
https://github.com/animo/react-native-ble-didcomm/pull/27#discussion_r1097171172

**Comment by blu3beri** [comment]
My preference still goes out to having them separated. Mainly because they both MUST be optional parameters and I see no advantage in combining them. Also, if we were to combine them, I would likely suggest to combine all of them as registering the (dis)connect listeners together, but the message listener not feels very weird. 

#### pseudo-code
```typescript
const registerOnConnectAndDisconnectListeners = (options: {onConnect?: (identifier: string) => void, onDisconnect?: (identifier: string) => void}) => {
  if(onConnect) registerListener(onConnect)
  if(onDisconnect) registerListener(onDisconnect)
}
```

vs 

```typescript
const registerOnConnectListened = (cb: (identifier: string) => void) {
  registerListener(cb)
}
const registerOnDisconnectListened = (cb: (identifier: string) => void) {
  registerListener(cb)
}
```

**Comment by blu3beri** [comment]
@morrieinmaas what is the state of this issue?
